In [1]:
import numpy as np

def load_numpy_array_data(file_path: str) -> np.array:
    """
    load numpy array data from file
    file_path: str location of file to load
    return: np.array data loaded
    """
    try:
        with open(file_path, 'rb') as file_obj:
            return np.load(file_obj, allow_pickle=True)
    except Exception as e:
        print(e)

In [2]:
train_arr = load_numpy_array_data("train.npy")
test_arr = load_numpy_array_data("test.npy")

In [9]:
train_arr.shape

(1007, 70)

In [7]:
train_arr

array([[0.0, 4.0, 1.0, ..., 0.0, 0.006837958556225857, 1],
       [4.0, 5.0, 1.0, ..., 0.0, 0.00729016198877025, 1],
       [4.0, 1.0, 0.0, ..., 0.0, 0.007011616445612056, 1],
       ...,
       [3.0, 4.0, 0.0, ..., 0.0, 0.006519616300173364, 1],
       [1.0, 5.0, 0.0, ..., 1.0, 0.007587674996831646, 0],
       [1.0, 2.0, 2.0, ..., 0.0, 0.007430324861242352, 1]], dtype=object)

In [10]:
test_arr.shape

(252, 42)

In [6]:
test_arr

array([[0.0, 1.0, 0.0, ..., 0.0, -0.04057240253917703, 1],
       [1.0, 2.0, 0.0, ..., 0.0, -0.5790631454531221, 1],
       [4.0, 5.0, 2.0, ..., 1.0, -0.7795141501901028, 0],
       ...,
       [2.0, 0.0, 1.0, ..., 0.0, -0.04057240253917703, 0],
       [2.0, 0.0, 1.0, ..., 0.0, 0.4207000726186286, 0],
       [4.0, 3.0, 0.0, ..., 0.0, -0.5790631454531221, 1]], dtype=object)

In [18]:
y_train

array([1, 1, 1, ..., 1, 0, 1], dtype=object)

In [20]:
from neuro_mf import ModelFactory
import numpy as np
from tqdm import tqdm

# Assuming train_arr and test_arr have already been loaded correctly
# Split the data into features (X) and target (y)
x_train, y_train = train_arr[:, :-1], train_arr[:, -1]
x_test, y_test = test_arr[:, :-1], test_arr[:, -1]
# Ensure y_train and y_test are numeric
y_train = y_train.astype(int)
y_test = y_test.astype(int)
# Create a ModelFactory instance using your model configuration file
model_factory = ModelFactory(model_config_path="model.yaml")

# Wrap the search process with a progress bar
with tqdm(total=100) as pbar:  # You may need to adjust the total to the actual number of iterations
    best_model_detail = model_factory.get_best_model(
        X=x_train,
        y=y_train,
        base_accuracy=60
    )
    # Update the progress bar accordingly during the search process
    pbar.update(10)  # Call this as needed to show progress

  0%|          | 0/100 [00:00<?, ?it/s]

Fitting 3 folds for each of 2160 candidates, totalling 6480 fits


  0%|          | 0/100 [27:52<?, ?it/s]


KeyboardInterrupt: 